School_77/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School_77.Models;
using School_77.ViewModels;

namespace School_77.Controllers
{
    public class CourseController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Course
        public ActionResult Index(int? id)
        {
            var viewModel = new CourseIndexData();
            viewModel.Courses = db.Courses
                .Include(i => i.Teacher)
                .OrderBy(i => i.Title);

            if (id != null)
            {
                ViewBag.CourseID = id.Value;
                viewModel.Students = viewModel.Courses.Where(
                    i => i.ID == id.Value).Single().Students.OrderBy(i => i.LastName);
            }

            return View(viewModel);
        }

        // GET: Course/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Course/Create
        public ActionResult Create()
        {
            PopulateTeachersDropDownList(null);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TeacherID,Title,Branch")] Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Courses.Add(course);
                    db.SaveChanges();
                    Teacher teacherToUpdate = db.Teachers.Find(course.TeacherID);
                    teacherToUpdate.CourseID = course.ID;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            ViewBag.TeacherID = new SelectList(db.People, "ID", "LastName", course.TeacherID);
            PopulateTeachersDropDownList(course.ID, course.TeacherID);
            return View(course);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            PopulateTeachersDropDownList(id, course.TeacherID);
            return View(course);
        }

 
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var courseToUpdate = db.Courses.Find(id);
            if (db.Teachers.Where(i => i.CourseID == id).Any()) 
            {
                Teacher teacherToUpdateOld = db.Teachers.Where(i => i.CourseID == id).Single();
                teacherToUpdateOld.CourseID = null;
            }          
            if (TryUpdateModel(courseToUpdate, "", 
                new string[] { "Title", "Branch", "TeacherID" }))
            {
                try
                {                   
                    db.SaveChanges();
                    courseToUpdate.Teacher.CourseID = id;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateTeachersDropDownList(id, courseToUpdate.TeacherID);
            return View(courseToUpdate);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            course.Teacher.CourseID = null;
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private void PopulateTeachersDropDownList(int? id, object selectedTeacher = null)
        {
            var teachersQuery = from d in db.Teachers.Where(i => i.Course == null || i.CourseID == id)
                                   orderby d.LastName
                                   select d;
            ViewBag.TeacherID = new SelectList(teachersQuery, "ID", "FullName", selectedTeacher);
        }
    }   
}

School_77/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web.Mvc;
using School_77.Models;
using School_77.ViewModels;

namespace School_77.Controllers
{
    public class GradesController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Grades
        [Obsolete]
        public ActionResult Index(int? id, int? SubjectID, string month, int? CourseID = 1)
        {
            
            var viewModel = new GradeIndexData();
            viewModel.TeacherID = id;
            viewModel.Grades = db.Grades.ToArray();
            PopulateCoursesDropDownList(id, db.Courses.Find(CourseID));
            PopulateSubjectsDropDownList(id, CourseID);

            var students = from m in db.Students
                           select m;
            DateTime Default = new DateTime(2022, 9, 5);
            if (CourseID != null && db.Schedules.Where(x => x.CourseID == CourseID && x.SubjectID == SubjectID).Any())
            {               
                viewModel.Students = students.Where(x => x.CourseID == CourseID).OrderBy(s => s.LastName);
                var NeedSchedules = db.Schedules.Where(x => x.CourseID == CourseID && x.SubjectID == SubjectID);
                //Понедельник
                viewModel.Monday = NeedSchedules.Where(x => x.DateDay == Default);
                //Вторник
                viewModel.Tuesday = NeedSchedules.Where(x => x.DateDay == EntityFunctions.AddDays(Default, 1));
                //Среда
                viewModel.Wednesday = NeedSchedules.Where(x => x.DateDay == EntityFunctions.AddDays(Default, 2));
                //Четверг
                viewModel.Thursday = NeedSchedules.Where(x => x.DateDay == EntityFunctions.AddDays(Default, 3));
                //Пятница
                viewModel.Friday = NeedSchedules.Where(x => x.DateDay == EntityFunctions.AddDays(Default, 4));
            }
            else {
                viewModel.Students = null;
                viewModel.Monday = new List<Schedule>();
                //Вторник
                viewModel.Tuesday = new List<Schedule>();
                //Среда
                viewModel.Wednesday = new List<Schedule>();
                //Четверг
                viewModel.Thursday = new List<Schedule>();
                //Пятница
                viewModel.Friday = new List<Schedule>();
            }

            if (SubjectID != null)
            {
                viewModel.Grades = viewModel.Grades.Where(x => x.SubjectID == SubjectID);
                PopulateSubjectsDropDownList(id, CourseID, db.Subjects.Find(SubjectID));
            }

            return View(viewModel);
        }

        [HttpPost]   
        public ActionResult Create(int studentID, int subjectID, int value, DateTime date)
        {
            Grade grade = new Grade { StudentID = studentID, SubjectID = subjectID, Value = value, Date = date };
            db.Grades.Add(grade);
            db.SaveChanges();
            int? course = db.Students.Find(studentID).CourseID;
            string monthRedirect = date.Year + "-" + date.Month;
            if (date.Month < 10) { monthRedirect = date.Year + "-0" + date.Month; }
            return RedirectToAction("Index", new { CourseID=course, SubjectID=subjectID, month= monthRedirect });
        }

        [HttpPost]
        public ActionResult Edit(int ID, int value)
        {
            Grade grade = db.Grades.Find(ID);

            string monthRedirect = grade.Date.Year + "-" + grade.Date.Month;
            if (grade.Date.Month < 10) { monthRedirect = grade.Date.Year + "-0" + grade.Date.Month; }
            int? courseRedirect = grade.Student.CourseID;
            int? subjectRedirect = grade.SubjectID;

            if (value != grade.Value)
            {
                if (value == 0)
                {
                    db.Grades.Remove(grade);
                }
                else
                {
                    grade.Value = value;                   
                }
                db.SaveChanges();
            }           
            return RedirectToAction("Index", new { CourseID = courseRedirect, SubjectID = subjectRedirect, month = monthRedirect });
        }

        private void PopulateCoursesDropDownList(int? TeacherID, object selectedCourse = null)
        {
            var CourseQuery = from d in db.Courses
                            orderby d.Title
                            select d;
            if (TeacherID != null) 
            {
                var CourseLst = from d in db.Schedules.Where(item => item.TeacherID == TeacherID)
                                 select d.Course;
                CourseQuery = CourseLst.Distinct().OrderBy(x => x.Title);
            }
            List<SelectListItem> MyCourseList = new List<SelectListItem>();
            MyCourseList.AddRange(new SelectList(CourseQuery, "ID", "Title", selectedCourse));
            MyCourseList.Insert(0, new SelectListItem { Text = "", Value = "" });
            ViewBag.CourseID = MyCourseList;
        }
        private void PopulateSubjectsDropDownList(int? TeacherID, int? courseID, object selectedSubject = null)
        {
            var SubjectLst = from d in db.Subjects.Where(item => item.ID == null)
                             orderby d.Name
                             select d;
            if (courseID != null)
            {
                var ScheduleQuery = from d in db.Schedules.Where(x => x.CourseID == courseID)
                                   select d;
                if (TeacherID != null) 
                {
                    ScheduleQuery = ScheduleQuery.Where(k => k.TeacherID == TeacherID);
                }
                var SubjectQuery = from d in ScheduleQuery
                                   select d.Subject;
                SubjectLst = SubjectQuery.Distinct().OrderBy(d => d.Name);
                
            }
            if (TeacherID != null) 
            {
                
            }
            SubjectLst.Append(new Subject { ID = 50, Name = "--Выберите--" });
            ViewBag.SubjectID = new SelectList(SubjectLst, "ID", "Name", selectedSubject);
        }
    }
}

School_77/Controllers/ParentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School_77.Models;
using School_77.ViewModels;

namespace School_77.Controllers
{
    public class ParentsController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Parents
        public ActionResult Index()
        {
            var viewModel = new ParentIndexData();
            viewModel.Parents = db.Parents.OrderBy(i => i.LastName);
            return View(viewModel);
        }

        // GET: Parents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parent parent = db.Parents.Find(id);
            if (parent == null)
            {
                return HttpNotFound();
            }
            return View(parent);
        }

        // GET: Parents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Parents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LastName,FirstName,Patronymic")] Parent parent)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(parent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(parent);
        }

        // GET: Parents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parent parent = db.Parents.Find(id);
            if (parent == null)
            {
                return HttpNotFound();
            }
            return View(parent);
        }

        // POST: Parents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LastName,FirstName,Patronymic")] Parent parent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parent);
        }

        // GET: Parents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parent parent = db.Parents.Find(id);
            if (parent == null)
            {
                return HttpNotFound();
            }
            return View(parent);
        }

        // POST: Parents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Parent parent = db.Parents.Find(id);
            db.People.Remove(parent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

School_77/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    .navbar {
        overflow: hidden;
    }

    .navbar-right{
        padding-right: 45px;
    }

    .login {
        font-size: 18px;
        padding-top: 15px;
        padding-bottom: 15px;
        line-height: 20px;
    }

    .drpdwn {
        -moz-appearance: none;
        -webkit-appearance: none;
        appearance: none;
        color: #FFFFFF;
        background-color: rgba(0, 0, 0, 0);
        text-align: center;
        border: 0px;
    }
    select option {
        background: rgb(51,51,51);
    }
    </style>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/school.png" class="img-center" height="50" width="50" />
                <a class="navbar-brand" href="/">School №77</a>
            </div>
            <div class="navbar-collapse collapse">
                <form id="login-drop" class="login navbar-right" action="/Home">
                    <select class="drpdwn" id="LoginID" name="LoginID" onchange="this.form.submit()">
                        <option selected="selected" disabled="disabled">Пользователь</option>
                        <option value="0">Администратор - #### #. #.</option>
                        <option value="47">Родитель - Баженов И. А.</option>
                        <option value="4">Ученик - Попова А. А.</option>
                        <option value="44">Учитель - Баранов А. Н.</option>
                    </select>
                </form>
            </div>
        </div>
    </div>

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tomsk Polytechnic University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School_77/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/layout.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/school.png" class="img-center" height="50" width="50" />
                <a class="navbar-brand" href="/">School №77</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Учителя", "Index", "Teacher")</li>
                    <li>@Html.ActionLink("Родители", "Index", "Parents")</li>
                    <li>@Html.ActionLink("Классы", "Index", "Course")</li>
                </ul>
                <form id="login-drop" class="login navbar-right" action="/Home">
                    <select class="drpdwn" id="LoginID" name="LoginID" onchange="this.form.submit()">
                        <option value="0" selected="selected">Администратор - #### #. #.</option>
                        <option value="47">Родитель - Баженов И. А.</option>
                        <option value="4">Ученик - Попова А. А.</option>
                        <option value="44">Учитель - Баранов А. Н.</option>
                    </select>
                </form>
            </div>
        </div>
    </div>

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tomsk Polytechnic University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School_77/Views/Shared/_LayoutParent.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/layout.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/school.png" class="img-center" height="50" width="50" />
                <a class="navbar-brand" href="/">School №77</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Дневник", "Student", "Schedule", new { id = 47 }, new { @class = "Link" })</li>
                </ul>
                <form id="login-drop" class="login navbar-right" action="/Home">
                    <select class="drpdwn" id="LoginID" name="LoginID" onchange="this.form.submit()">
                        <option value="0">Администратор - #### #. #.</option>
                        <option value="47" selected="selected">Родитель - Баженов И. А.</option>
                        <option value="4">Ученик - Попова А. А.</option>
                        <option value="44">Учитель - Баранов А. Н.</option>
                    </select>
                </form>
            </div>
        </div>
    </div>

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tomsk Polytechnic University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School_77/Views/Shared/_LayoutStudent.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/layout.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/school.png" class="img-center" height="50" width="50" />
                <a class="navbar-brand" href="/">School №77</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Дневник", "Student", "Schedule", new { id = 4 }, new { @class = "Link" })</li>
                </ul>
                <form id="login-drop" class="login navbar-right" action="/Home">
                    <select class="drpdwn" id="LoginID" name="LoginID" onchange="this.form.submit()">
                        <option value="0">Администратор - #### #. #.</option>
                        <option value="47">Родитель - Баженов И. А.</option>
                        <option value="4" selected="selected">Ученик - Попова А. А.</option>
                        <option value="44">Учитель - Баранов А. Н.</option>
                    </select>
                </form>
            </div>
        </div>
    </div>

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tomsk Polytechnic University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School_77/Views/Shared/_LayoutTeacher.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/layout.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/school.png" class="img-center" height="50" width="50" />
                <a class="navbar-brand" href="/">School №77</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Расписание", "Teacher", "Schedule", new { id = 44 }, new { @class = "Link" })</li>
                    <li>@Html.ActionLink("Журнал", "Index", "Grades", new { id = 44 }, new { @class = "Link" })</li>
                </ul>
                <form id="login-drop" class="login navbar-right" action="/Home">
                    <select class="drpdwn" id="LoginID" name="LoginID" onchange="this.form.submit()">
                        <option value="0">Администратор - #### #. #.</option>
                        <option value="47">Родитель - Баженов И. А.</option>
                        <option value="4">Ученик - Попова А. А.</option>
                        <option value="44" selected="selected">Учитель - Баранов А. Н.</option>
                    </select>
                </form>
            </div>
        </div>
    </div>

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2022 - Tomsk Polytechnic University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>