School_77/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using School_77.Models;

namespace School_77.Models
{
    public class Schedule
    {
        public int ID { get; set; }
        [Range(1, 5)]
        public int Order { get; set; }
        public int CourseID { get; set; }
        public virtual Course Course { get; set; }
        public int SubjectID { get; set; }
        public virtual Subject Subject { get; set; }
        public int TeacherID { get; set; }
        public virtual Teacher Teacher { get; set; }
        public DateTime DateDay { get; set; }
        
    }
}

School_77/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace School_77.Models
{
    public class Student : Person
    {
        public int? CourseID { get; set; }
        [Display(Name = "Класс")]
        public virtual Course Course { get; set; }

    }
}

School_77/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace School_77.Models
{
    public class Teacher : Person
    {
        public int? CourseID { get; set; }
        [Display(Name = "Класс")]
        public virtual Course Course { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}

School_77/Controllers/ScheduleController.cs
using School_77.Models;
using School_77.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace School_77.Controllers
{
    public class ScheduleController : Controller
    {
        private SchoolContext db = new SchoolContext();
        // GET: Schedule
        public ActionResult Student(int? id, int? PersonID, string calendar)
        {
            var viewModel = new ScheduleIndexData();
            viewModel.Schedules = db.Schedules;
            if (id != null)
            {
                viewModel.Id = id;
                Person person = db.People.Find(id);
                if (person.GetType().Name.Contains("Parent"))
                {
                    PopulatePersonDropDownList(id, "Parent", viewModel);
                }
                else 
                { 
                    PersonID = id;
                    PopulatePersonDropDownList(id, "Student", viewModel);
                }                
            }
            viewModel.Grades = db.Grades
                .OrderBy(p => p.ID)
                .ToArray();         
            
            FillSchedule(PersonID, "Student", viewModel, calendar);
            return View(viewModel); 
        }

        public ActionResult Teacher(int? id, int? PersonID, string calendar)
        {
            var viewModel = new ScheduleIndexData();
            viewModel.Schedules = db.Schedules;

            if (id != null)
            {
                PersonID = id;
                PopulatePersonDropDownList(id, "Teacher", viewModel);
            }
            
            FillSchedule(PersonID, "Teacher", viewModel, calendar);
            return View(viewModel);
        }
        private void FillSchedule(int? PersonID, string type, ScheduleIndexData viewModel, string calendar)
        {
            if (type == "Student" && PersonID != null)
            {
                int? courseID = db.Students.Find(PersonID).CourseID;
                viewModel.Schedules = viewModel.Schedules.Where(x => x.CourseID == courseID);
                viewModel.Grades = viewModel.Grades.Where(x => x.StudentID == PersonID);
            }

            else if (type == "Teacher" && PersonID != null)
            {
                viewModel.Schedules = viewModel.Schedules.Where(x => x.TeacherID == PersonID);
            }

            if (!String.IsNullOrEmpty(calendar))
            {
                int year = Int32.Parse(calendar.Substring(0, 4));
                int week = Int32.Parse(calendar.Substring(6, 2));
                DateTime Default = new DateTime(2022, 9, 5);

                viewModel.Schedules = viewModel.Schedules.Where(s => s.DateDay >= Default && s.DateDay <= Default.AddDays(5));
                //Понедельник
                if (viewModel.Schedules.Where(s => s.DateDay == Default).Any())
                {
                    viewModel.Monday = viewModel.Schedules.Where(s => s.DateDay == Default);
                }
                //Вторник
                if (viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(1)).Any())
                {
                    viewModel.Tuesday = viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(1));
                }
                //Среда
                if (viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(2)).Any())
                {
                    viewModel.Wednesday = viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(2));
                }
                //Четверг
                if (viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(3)).Any())
                {
                    viewModel.Thursday = viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(3));
                }
                //Пятница
                if (viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(4)).Any())
                {
                    viewModel.Friday = viewModel.Schedules.Where(s => s.DateDay == Default.AddDays(4));
                }
            }
        }
        private void PopulatePersonDropDownList(int? id, string type, ScheduleIndexData viewModel)
        {
            viewModel.Id = id;
            viewModel.PersonType = type;
            Person person = db.People.Find(id);
            if (type == "Parent")
            {
                Parent parent = (Parent) person;
                var PersonQry = from d in parent.Kids
                                    orderby d.LastName
                                    select d;
                ViewBag.PersonID = new SelectList(PersonQry, "ID", "Initials");
            }
            else if (type == "Student")
            {
                var PersonQry = from d in db.Students.Where(x => x.ID == id)
                                    orderby d.LastName
                                    select d;
                ViewBag.PersonID = new SelectList(PersonQry, "ID", "Initials");
            }
            else if (type == "Teacher")
            {
                var PersonQry = from d in db.Teachers.Where(x => x.ID == id)
                                 orderby d.LastName
                                 select d;
                ViewBag.PersonID = new SelectList(PersonQry, "ID", "Initials");
            }
        }
    }
}

School_77/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using School_77.Models;
using School_77.ViewModels;
using PagedList;
using System.Data.Entity.Infrastructure;

namespace School_77.Controllers
{
    public class StudentsController : Controller
    {
        private SchoolContext db = new SchoolContext();

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.ClassSortParm = String.IsNullOrEmpty(sortOrder) ? "class_desc" : "";
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            var students = from s in db.Students
                           select s;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString) || s.Patronymic.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.LastName);
                    break;
                case "name":
                    students = students.OrderBy(s => s.LastName);
                    break;
                case "class_desc":
                    students = students.OrderByDescending(s => s.Course.Title);
                    break;
                default:
                    students = students.OrderBy(s => s.Course.Title);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        public ActionResult Create()
        {
            PopulateCoursesDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,LastName,FirstName,Patronymic")] Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Students.Add(student);
                    db.SaveChanges();
                    RedirectToAction("Index", "Course");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "ID", "Title", student.CourseID);
            PopulateCoursesDropDownList(student.CourseID);
            return View(student);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            PopulateCoursesDropDownList();
            return View(student);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var studentToUpdate = db.Students.Find(id);
            if (TryUpdateModel(studentToUpdate, "",
                new string[] { "LastName", "FirstName", "Patronymic", "CourseID" }))
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index", "Course");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateCoursesDropDownList(studentToUpdate.CourseID);
            return View(studentToUpdate);
        }

        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Student student = db.Students.Find(id);
                db.Students.Remove(student);
                db.SaveChanges();
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index", "Course");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private void PopulateCoursesDropDownList(object selectedCourse = null)
        {
            var coursesQuery = from d in db.Courses
                                orderby d.Title
                                select d;
            ViewBag.CourseID = new SelectList(coursesQuery, "ID", "Title", selectedCourse);
        }
    }
}

School_77/Views/Schedule/Student.cshtml
@model School_77.ViewModels.ScheduleIndexData
@if (Model.PersonType == "Parent")
{ Layout = "~/Views/Shared/_LayoutParent.cshtml"; }
else if (Model.PersonType == "Student")
{ Layout = "~/Views/Shared/_LayoutStudent.cshtml"; }
@{
    ViewBag.Title = "Дневник";
}
@{
    List<string> time = new List<string> { "8:00 - 8:40", "8:50 - 9:30", "9:40 - 10:20", "10:30 - 11:10", "11:30 - 12:10" };
    List<string> WeekDay = new List<string> { "Понедельник", "Вторник", "Среда", "Четверг", "Пятница" };
    List<IEnumerable<School_77.Models.Schedule>> Days = new List<IEnumerable<School_77.Models.Schedule>>
    {
        Model.Monday, Model.Tuesday, Model.Wednesday, Model.Thursday, Model.Friday
    };

    string calendarRaw = Context.Request.QueryString["calendar"];
    string student = Context.Request.QueryString["PersonID"];
    if (Model.PersonType == "Student")
    {
        student = Model.Id.ToString();
    }
    int year = 2022;
    int week = 0;
    DateTime ToDay = new DateTime(year, 1, 3);
    if (calendarRaw != null && calendarRaw.Length == 8)
    {
        year = Int32.Parse(calendarRaw.Substring(0, 4));
        week = Int32.Parse(calendarRaw.Substring(6, 2));
        DateTime jan1 = new DateTime(year, 1, 1);
        ToDay = jan1.AddDays(week * 7 - 5);
    }
    string next = "https://localhost:44382/Schedule/Student/"+ Model.Id + "?PersonID=" + student + "&calendar=2022-W" + (week + 1).ToString("00");
    string previous = "https://localhost:44382/Schedule/Student/" + Model.Id + "?PersonID=" + student + "&calendar=2022-W" + (week - 1).ToString("00");
    if (week < 1) { previous = "https://localhost:44382/Schedule/Student/" + Model.Id + "?PersonID=" + student + "&calendar=2022-W00"; }
}
<body>
    @using (Html.BeginForm("Student", "Schedule", FormMethod.Get))
    {
        <table border="0">
            <tr class="upper">
                <th align="center">
                    <font size="5" color=#222>Расписание занятий</font>
                    @Html.DropDownList("PersonID", null, htmlAttributes: new { @onchange = "this.form.submit()" })
                </th>
            </tr>
        </table>
        <br />
        <ul class="pager">
            <li class="previous">
                <a href=@previous>← Предыдущая неделя</a>
            </li>
            <li>
                <input type="week" name="calendar" onchange='this.form.submit()' value=@calendarRaw max="2022-W52" min="2022-W01">
            </li>
            <li class="next">
                <a href=@next>Следующая неделя →</a>
            </li>
        </ul>
    }
    @if (!(String.IsNullOrEmpty(calendarRaw) || String.IsNullOrEmpty(student)))
    {
        <table width="1200" border="2" id="basic">
            @for (int date = 0; date < 5; date++)
            {
                for (int i = 0; i < 5; i++)
                {
                <tr>
                    @if(i == 0)
                    {
                        <td class="Data" rowspan=5>@ToDay.ToString("dd.MM")</td>
                    <td class="Day" rowspan=5>@WeekDay[date]</td>
                    }           
                    <td class="Order">
                        @(i+1)
                    </td>
                    <td class="Time">
                        @time[i]
                    </td>
                    @if ((Days[date] != null) && (Days[date].Where(x => x.Order == i + 1).Any()))
                    {
                        int OrderSubjID = Days[date].Where(k => k.Order == i + 1).SingleOrDefault().SubjectID;
                        School_77.Models.Grade OrderGrade = Model.Grades.SingleOrDefault(x => x.SubjectID == OrderSubjID && x.Date == ToDay);
                        <td id="Subject">
                            @Days[date].Where(x => x.Order == i+1).SingleOrDefault().Subject.Name
                        </td>
                        <td class="grade">
                            @if (OrderGrade != null)
                            {
                                @OrderGrade.Value
                            }
                        </td>
                    }
                    else
                    {
                        <td id="Subject"></td>
                    }
                </tr>
                }
                ToDay = ToDay.AddDays(1);
            }
            <tr><td colspan="6"><br></td></tr>
            <tr>
                <td class="Data" rowspan=5>@ToDay.AddDays(1).ToString("dd.MM")</td>
                <td class="Day" rowspan=5>Суббота</td>
                <td id="Holiday" colspan="4">
                </td>
            </tr>
            @for (int i = 2; i <= 5; i++)
            {
                <tr>
                    <td id="Holiday" colspan="4">
                    </td>
                </tr>
            }
        </table>
        <br />
    }
</body>

<link rel="stylesheet" href="~/Content/schedule.css">

@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $("#PersonID").each(function () {
        if ($('option', this).length < 2)
        {
            this.disabled = true;
        }
    });
</script>

School_77/Views/Schedule/Teacher.cshtml
@model School_77.ViewModels.ScheduleIndexData
@{
    ViewBag.Title = "Дневник";
}
@{ Layout = "~/Views/Shared/_LayoutTeacher.cshtml"; }
@{
    List<string> time = new List<string> { "8:00 - 8:40", "8:50 - 9:30", "9:40 - 10:20", "10:30 - 11:10", "11:30 - 12:10" };
    List<string> DayName = new List<string> { "Понедельник", "Вторник", "Среда", "Четверг", "Пятница" };
    List<IEnumerable<School_77.Models.Schedule>> Days = new List<IEnumerable<School_77.Models.Schedule>>
    {
        Model.Monday, Model.Tuesday, Model.Wednesday, Model.Thursday, Model.Friday
    };

    string calendarRaw = Context.Request.QueryString["calendar"];
    string teacher = Context.Request.QueryString["PersonID"];
    if (Model.Id != null)
    {
        teacher = Model.Id.ToString();
    }
    int year = 2022;
    int week = 0;
    DateTime ToDay = new DateTime(year, 1, 3);
    if (calendarRaw != null && calendarRaw.Length == 8)
    {
        year = Int32.Parse(calendarRaw.Substring(0, 4));
        week = Int32.Parse(calendarRaw.Substring(6, 2));
        DateTime jan1 = new DateTime(year, 1, 1);
        ToDay = jan1.AddDays(week * 7 - 5);
    }
    string next = "https://localhost:44382/Schedule/Teacher/" + Model.Id + "?TPersonID=" + teacher + "&calendar=2022-W" + (week + 1).ToString("00");
    string previous = "https://localhost:44382/Schedule/Teacher/" + Model.Id + "?PersonID=" + teacher + "&calendar=2022-W" + (week - 1).ToString("00");
    if (week < 1) { previous = "https://localhost:44382/Schedule/Teacher/" + Model.Id + "?PersonID=" + teacher + "&calendar=2022-W00"; }
}
<body>
    @using (Html.BeginForm("Teacher", "Schedule", FormMethod.Get))
    {
        <table border="0">
            <tr class="upper">
                <th align="center">
                    <font size="5" color=#222>Расписание занятий</font>
                    @Html.DropDownList("PersonID", null, htmlAttributes: new { @onchange = "this.form.submit()" })
                </th>
            </tr>
        </table>
        <br />
        <ul class="pager">
            <li class="previous">
                <a href=@previous>← Предыдущая неделя</a>
            </li>
            <li>
                <input type="week" name="calendar" onchange='this.form.submit()' value=@calendarRaw max="2022-W52" min="2022-W01">
            </li>
            <li class="next">
                <a href=@next>Следующая неделя →</a>
            </li>
        </ul>
    }
    @if (!(String.IsNullOrEmpty(calendarRaw) || String.IsNullOrEmpty(teacher)))
    {
        <table width="1200" border="2" id="basic">
            @for (int date = 0; date < 5; date++)
            {
                for (int i = 0; i < 5; i++)
                {
                    <tr>
                        @if (i == 0)
                        {
                            <td class="Data" rowspan=5>@ToDay.ToString("dd.MM")</td>
                            <td class="Day" rowspan=5>@DayName[date]</td>
                        }
                        <td class="Order">
                            @(i+1)
                        </td>
                        <td class="Time">
                            @time[i]
                        </td>
                        @if ((Days[date] != null) && (Days[date].Where(x => x.Order == i+1).Any()))
                        {
                            <td id="Subject">
                                @Days[date].Where(x => x.Order == i + 1).SingleOrDefault().Subject.Name
                            </td>
                            <td class="course">
                                @Days[date].Where(x => x.Order == i + 1).SingleOrDefault().Course.Title
                            </td>
                        }
                        else
                        {
                            <td id="Subject"></td>
                        }
                    </tr>
                }
                ToDay = ToDay.AddDays(1);
            }
            <tr><td colspan="6"><br></td></tr>
            <tr>
                <td class="Data" rowspan=5>@ToDay.AddDays(1).ToString("dd.MM")</td>
                <td class="Day" rowspan=5>Суббота</td>
                <td id="Holiday" colspan="4">
                </td>
            </tr>
            @for (int i = 2; i <= 5; i++)
            {
                <tr>
                    <td id="Holiday" colspan="4">
                    </td>
                </tr>
            }
        </table>
        <br />
    }
</body>
<link rel="stylesheet" href="~/Content/schedule.css">
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $("#PersonID").each(function () {
        if ($('option', this).length < 2) {
            this.disabled = true;
        }
    });
</script>